# -*- coding: utf-8 -*-
"""Словарь курса, часть 1 (темы 1-10).

Формат слова: (en, ru, tr, example_en, example_ru)
  en  - английское слово или готовая фраза
  ru  - перевод (через запятую, если есть варианты)
  tr  - приблизительная русская транскрипция, ударный слог ЗАГЛАВНЫМИ
  example_en / example_ru - пример употребления с переводом
"""

TOPICS = [
    {
        "id": "greetings",
        "title": "Приветствия",
        "emoji": "👋",
        "words": [
            ("hello", "привет, здравствуйте", "хэлОу",
             "Hello! How are you?", "Привет! Как дела?"),
            ("hi", "привет (неформально)", "хАй",
             "Hi, Kate! Nice to see you.", "Привет, Кейт! Рад тебя видеть."),
            ("good morning", "доброе утро", "гуд мОонинг",
             "Good morning, mum!", "Доброе утро, мама!"),
            ("good afternoon", "добрый день", "гуд афтэнУун",
             "Good afternoon, Mr Brown.", "Добрый день, мистер Браун."),
            ("good evening", "добрый вечер", "гуд Ивнинг",
             "Good evening! Nice to see you.", "Добрый вечер! Рад вас видеть."),
            ("goodbye", "до свидания", "гудбАй",
             "Goodbye! See you tomorrow.", "До свидания! До завтра."),
            ("bye", "пока", "бай",
             "Bye! Have a nice day!", "Пока! Хорошего дня!"),
            ("how are you?", "как дела?", "хАу а ю",
             "Hi, Tom! How are you?", "Привет, Том! Как дела?"),
            ("I am fine, thanks", "у меня всё хорошо, спасибо", "ай эм фАйн, сэнкс",
             "I am fine, thanks. And you?", "У меня всё хорошо, спасибо. А ты?"),
            ("see you later", "увидимся позже", "си: ю лЭйтэ",
             "See you later, Ann!", "Увидимся позже, Энн!"),
        ],
    },
    {
        "id": "intro",
        "title": "Знакомство и вежливость",
        "emoji": "🤝",
        "words": [
            ("my name is", "меня зовут", "май нЭйм из",
             "My name is Anna.", "Меня зовут Анна."),
            ("what is your name?", "как тебя зовут?", "уОт из ё нЭйм",
             "Hello! What is your name?", "Привет! Как тебя зовут?"),
            ("I am", "я (есть)", "ай эм",
             "I am from Russia.", "Я из России."),
            ("nice to meet you", "приятно познакомиться", "нАйс ту мИ:т ю",
             "Nice to meet you, Ivan!", "Приятно познакомиться, Иван!"),
            ("this is", "это (при знакомстве)", "Зис из",
             "This is my friend Pavel.", "Это мой друг Павел."),
            ("friend", "друг", "фрэнд",
             "He is my best friend.", "Он мой лучший друг."),
            ("excuse me", "извините (чтобы обратиться)", "иксКЬЮ:з ми",
             "Excuse me, are you Mr Black?", "Извините, вы мистер Блэк?"),
            ("sorry", "извините, простите", "сОри",
             "Sorry, I am late.", "Извините, я опоздал."),
            ("please", "пожалуйста (просьба)", "пли:з",
             "Please, sit down.", "Пожалуйста, садитесь."),
            ("thank you", "спасибо", "сЭнк ю",
             "Thank you very much!", "Большое спасибо!"),
        ],
    },
    {
        "id": "people",
        "title": "Я и другие (местоимения)",
        "emoji": "🙋",
        "words": [
            ("I", "я", "ай",
             "I am a student.", "Я студент."),
            ("you", "ты, вы", "ю:",
             "You are my friend.", "Ты мой друг."),
            ("he", "он", "хи:",
             "He is a doctor.", "Он врач."),
            ("she", "она", "ши:",
             "She is at home.", "Она дома."),
            ("it", "оно, это", "ит",
             "It is a cat.", "Это кошка."),
            ("we", "мы", "уи:",
             "We are a family.", "Мы семья."),
            ("they", "они", "Зэй",
             "They are from London.", "Они из Лондона."),
            ("man", "мужчина, человек", "мэн",
             "That man is my boss.", "Тот мужчина - мой начальник."),
            ("woman", "женщина", "уУмэн",
             "The woman is a teacher.", "Эта женщина - учитель."),
            ("child", "ребёнок", "чайлд",
             "The child is sleeping.", "Ребёнок спит."),
        ],
    },
    {
        "id": "family",
        "title": "Семья",
        "emoji": "👨‍👩‍👧",
        "words": [
            ("mother (mum)", "мама", "мАЗэ (мам)",
             "My mother is a nurse.", "Моя мама - медсестра."),
            ("father (dad)", "папа", "фАаЗэ (дэд)",
             "My father works in an office.", "Мой папа работает в офисе."),
            ("sister", "сестра", "сИстэ",
             "I have one sister.", "У меня одна сестра."),
            ("brother", "брат", "брАЗэ",
             "His brother is ten.", "Его брату десять."),
            ("son", "сын", "сан",
             "Their son goes to school.", "Их сын ходит в школу."),
            ("daughter", "дочь", "дОотэ",
             "Her daughter is a student.", "Её дочь студентка."),
            ("grandmother (grandma)", "бабушка", "грЭнмаЗэ (грЭнма)",
             "My grandmother lives in the country.", "Моя бабушка живёт в деревне."),
            ("grandfather (grandpa)", "дедушка", "грЭнфааЗэ (грЭнпа)",
             "Grandpa is eighty.", "Дедушке восемьдесят."),
            ("husband", "муж", "хАзбэнд",
             "Her husband is a driver.", "Её муж - водитель."),
            ("wife", "жена", "уАйф",
             "My wife likes tea.", "Моя жена любит чай."),
        ],
    },
    {
        "id": "numbers",
        "title": "Числа",
        "emoji": "🔢",
        "words": [
            ("one", "один", "уан",
             "I have one brother.", "У меня один брат."),
            ("two", "два", "ту:",
             "She has two cats.", "У неё две кошки."),
            ("three", "три", "сри:",
             "There are three apples on the table.", "На столе три яблока."),
            ("four", "четыре", "фо:",
             "The table has four chairs.", "За столом четыре стула."),
            ("five", "пять", "файв",
             "I work five days a week.", "Я работаю пять дней в неделю."),
            ("six", "шесть", "сикс",
             "My son is six.", "Моему сыну шесть."),
            ("seven", "семь", "сЭвн",
             "The lesson starts at seven.", "Урок начинается в семь."),
            ("eight", "восемь", "эйт",
             "I sleep eight hours.", "Я сплю восемь часов."),
            ("nine", "девять", "найн",
             "The shop opens at nine.", "Магазин открывается в девять."),
            ("ten", "десять", "тен",
             "This book costs ten dollars.", "Эта книга стоит десять долларов."),
            ("eleven", "одиннадцать", "илЭвн",
             "My daughter is eleven.", "Моей дочери одиннадцать."),
            ("twelve", "двенадцать", "туЭлв",
             "There are twelve months in a year.", "В году двенадцать месяцев."),
            ("twenty", "двадцать", "туЭнти",
             "I have twenty students.", "У меня двадцать учеников."),
            ("hundred", "сто", "хАндрэд",
             "There are a hundred people here.", "Здесь сто человек."),
        ],
    },
    {
        "id": "colors",
        "title": "Цвета",
        "emoji": "🎨",
        "words": [
            ("red", "красный", "рэд",
             "I have a red car.", "У меня красная машина."),
            ("blue", "синий, голубой", "блу:",
             "The sky is blue.", "Небо синее."),
            ("green", "зелёный", "гри:н",
             "The tree is green.", "Дерево зелёное."),
            ("yellow", "жёлтый", "йЭлоу",
             "She likes yellow flowers.", "Она любит жёлтые цветы."),
            ("black", "чёрный", "блэк",
             "My phone is black.", "Мой телефон чёрный."),
            ("white", "белый", "уайт",
             "He wears a white shirt.", "Он носит белую рубашку."),
            ("brown", "коричневый", "браун",
             "The table is brown.", "Стол коричневый."),
            ("orange", "оранжевый", "Ориндж",
             "I drink orange juice.", "Я пью апельсиновый сок."),
            ("grey", "серый", "грэй",
             "The weather is grey today.", "Сегодня погода серая."),
            ("pink", "розовый", "пинк",
             "Her dress is pink.", "Её платье розовое."),
        ],
    },
    {
        "id": "things",
        "title": "Вещи вокруг",
        "emoji": "📦",
        "words": [
            ("book", "книга", "бук",
             "This book is interesting.", "Эта книга интересная."),
            ("table", "стол", "тЭйбл",
             "The keys are on the table.", "Ключи на столе."),
            ("chair", "стул", "чЭэ",
             "Please, take a chair.", "Пожалуйста, возьмите стул."),
            ("phone", "телефон", "фОун",
             "My phone is in the bag.", "Мой телефон в сумке."),
            ("bag", "сумка, пакет", "бэг",
             "This bag is very heavy.", "Эта сумка очень тяжёлая."),
            ("pen", "ручка", "пен",
             "Can I take your pen?", "Можно взять вашу ручку?"),
            ("key", "ключ", "ки:",
             "I cannot find my key.", "Я не могу найти свой ключ."),
            ("cup", "чашка", "кап",
             "A cup of tea, please.", "Чашку чая, пожалуйста."),
            ("window", "окно", "уИндоу",
             "Open the window, please.", "Откройте окно, пожалуйста."),
            ("door", "дверь", "до:",
             "The door is open.", "Дверь открыта."),
        ],
    },
    {
        "id": "food",
        "title": "Еда и напитки",
        "emoji": "🍎",
        "words": [
            ("bread", "хлеб", "брэд",
             "I buy bread every day.", "Я покупаю хлеб каждый день."),
            ("milk", "молоко", "милк",
             "The child drinks milk.", "Ребёнок пьёт молоко."),
            ("cheese", "сыр", "чи:з",
             "I like cheese and bread.", "Я люблю сыр с хлебом."),
            ("meat", "мясо", "ми:т",
             "We eat meat and rice.", "Мы едим мясо с рисом."),
            ("fish", "рыба", "фиш",
             "My father likes fish.", "Мой папа любит рыбу."),
            ("apple", "яблоко", "Эпл",
             "An apple a day is good.", "Яблоко в день - это полезно."),
            ("egg", "яйцо", "эг",
             "I eat two eggs for breakfast.", "Я ем два яйца на завтрак."),
            ("water", "вода", "уОотэ",
             "A bottle of water, please.", "Бутылку воды, пожалуйста."),
            ("tea", "чай", "ти:",
             "Do you want tea or coffee?", "Ты хочешь чай или кофе?"),
            ("coffee", "кофе", "кОфи",
             "I drink coffee in the morning.", "Я пью кофе утром."),
            ("rice", "рис", "райс",
             "She cooks rice with fish.", "Она готовит рис с рыбой."),
            ("soup", "суп", "су:п",
             "The soup is very tasty.", "Суп очень вкусный."),
        ],
    },
    {
        "id": "meal",
        "title": "Приём пищи",
        "emoji": "🍽",
        "words": [
            ("breakfast", "завтрак", "брЭкфэст",
             "Breakfast is at eight.", "Завтрак в восемь."),
            ("lunch", "обед", "ланч",
             "I have lunch at work.", "Я обедаю на работе."),
            ("dinner", "ужин", "дИнэ",
             "Dinner is ready!", "Ужин готов!"),
            ("hungry", "голодный", "хАнгри",
             "I am hungry. Let us eat.", "Я голоден. Давай поедим."),
            ("thirsty", "хочется пить", "сЁсти",
             "The child is thirsty.", "Ребёнок хочет пить."),
            ("eat", "есть, кушать", "и:т",
             "We eat at home.", "Мы едим дома."),
            ("drink", "пить", "дринк",
             "He drinks a lot of water.", "Он пьёт много воды."),
            ("cook", "готовить", "кук",
             "My wife cooks very well.", "Моя жена очень хорошо готовит."),
            ("tasty", "вкусный", "тЭйсти",
             "This cake is tasty.", "Этот торт вкусный."),
            ("menu", "меню", "мЭнью:",
             "Can I see the menu?", "Можно посмотреть меню?"),
        ],
    },
    {
        "id": "time",
        "title": "Время",
        "emoji": "⏰",
        "words": [
            ("day", "день", "дэй",
             "Every day I study English.", "Каждый день я учу английский."),
            ("week", "неделя", "уи:к",
             "A week has seven days.", "В неделе семь дней."),
            ("month", "месяц", "манс",
             "I will come next month.", "Я приеду в следующем месяце."),
            ("year", "год", "йИэ",
             "Happy New Year!", "С Новым годом!"),
            ("today", "сегодня", "тудЭй",
             "Today is Monday.", "Сегодня понедельник."),
            ("tomorrow", "завтра", "тумОроу",
             "See you tomorrow!", "До завтра!"),
            ("yesterday", "вчера", "йЭстэдэй",
             "Yesterday it was cold.", "Вчера было холодно."),
            ("morning", "утро", "мОонинг",
             "I run in the morning.", "Я бегаю утром."),
            ("evening", "вечер", "Ивнинг",
             "In the evening we watch films.", "Вечером мы смотрим фильмы."),
            ("night", "ночь", "найт",
             "Good night!", "Спокойной ночи!"),
            ("hour", "час", "Ауэ",
             "The lesson is one hour.", "Урок длится один час."),
            ("minute", "минута", "мИнит",
             "Wait five minutes, please.", "Подождите пять минут, пожалуйста."),
        ],
    },
]
