# -*- coding: utf-8 -*-
"""Словарь курса, часть 3 (темы 21-30). Формат см. words1.py."""

TOPICS = [
    {
        "id": "seasons",
        "title": "Времена года",
        "emoji": "🍂",
        "words": [
            ("spring", "весна", "спринг",
             "In spring it is warm.", "Весной тепло."),
            ("summer", "лето", "сАмэ",
             "We go to the sea in summer.", "Летом мы едем на море."),
            ("autumn", "осень", "Оотэм",
             "Autumn is beautiful.", "Осень красивая."),
            ("winter", "зима", "уИнтэ",
             "Winter is cold here.", "Здесь холодная зима."),
            ("season", "время года, сезон", "сИ:зн",
             "My favourite season is summer.", "Моё любимое время года - лето."),
            ("birthday", "день рождения", "бЁсдэй",
             "My birthday is in May.", "Мой день рождения в мае."),
            ("flower", "цветок", "флАуэ",
             "She likes red flowers.", "Она любит красные цветы."),
            ("leaf", "лист (растения)", "ли:ф",
             "The leaves are yellow in autumn.", "Осенью листья жёлтые."),
            ("grass", "трава", "граас",
             "The children play on the grass.", "Дети играют на траве."),
            ("picnic", "пикник", "пИкник",
             "Let us have a picnic on Sunday.", "Давай устроим пикник в воскресенье."),
        ],
    },
    {
        "id": "months",
        "title": "Месяцы",
        "emoji": "🗓",
        "words": [
            ("January", "январь", "джЭньюэри",
             "January is the first month.", "Январь - первый месяц."),
            ("February", "февраль", "фЭбруэри",
             "It is very cold in February.", "В феврале очень холодно."),
            ("March", "март", "ма:ч",
             "Spring starts in March.", "Весна начинается в марте."),
            ("April", "апрель", "Эйприл",
             "It often rains in April.", "В апреле часто идут дожди."),
            ("May", "май", "мэй",
             "My holiday starts in May.", "Мой отпуск начинается в мае."),
            ("June", "июнь", "джу:н",
             "In June the days are long.", "В июне дни длинные."),
            ("July", "июль", "джулАй",
             "July is the hottest month.", "Июль - самый жаркий месяц."),
            ("August", "август", "О:гэст",
             "We rest in August.", "Мы отдыхаем в августе."),
            ("September", "сентябрь", "сэптЭмбэ",
             "School starts in September.", "Школа начинается в сентябре."),
            ("October", "октябрь", "октОубэ",
             "October is my favourite month.", "Октябрь - мой любимый месяц."),
            ("November", "ноябрь", "ноУЭмбэ",
             "In November it is grey and cold.", "В ноябре серо и холодно."),
            ("December", "декабрь", "дисЭмбэ",
             "December is a holiday month.", "Декабрь - праздничный месяц."),
        ],
    },
    {
        "id": "work",
        "title": "Работа",
        "emoji": "💼",
        "words": [
            ("job", "работа (место)", "джоб",
             "I like my job.", "Мне нравится моя работа."),
            ("office", "офис", "Офис",
             "I work in an office.", "Я работаю в офисе."),
            ("boss", "начальник", "бос",
             "My boss is very busy.", "Мой начальник очень занят."),
            ("colleague", "коллега", "кОли:г",
             "My colleague speaks English.", "Мой коллега говорит по-английски."),
            ("salary", "зарплата", "сЭлэри",
             "The salary is good.", "Зарплата хорошая."),
            ("meeting", "встреча, совещание", "мИ:тинг",
             "The meeting starts at ten.", "Совещание начинается в десять."),
            ("busy", "занятой", "бИзи",
             "I am busy today.", "Я сегодня занят."),
            ("free", "свободный, бесплатный", "фри:",
             "Are you free on Friday?", "Ты свободен в пятницу?"),
            ("team", "команда", "ти:м",
             "Our team is strong.", "Наша команда сильная."),
            ("experience", "опыт", "икспИэриэнс",
             "I have five years of experience.", "У меня пять лет опыта."),
        ],
    },
    {
        "id": "hobby",
        "title": "Хобби и свободное время",
        "emoji": "⚽",
        "words": [
            ("hobby", "хобби", "хОби",
             "My hobby is music.", "Моё хобби - музыка."),
            ("sport", "спорт", "спо:т",
             "I do sport three times a week.", "Я занимаюсь спортом три раза в неделю."),
            ("football", "футбол", "фУтбо:л",
             "We play football on Sunday.", "Мы играем в футбол в воскресенье."),
            ("music", "музыка", "мЬЮ:зик",
             "I listen to music in the car.", "Я слушаю музыку в машине."),
            ("film", "фильм", "филм",
             "This film is very good.", "Этот фильм очень хороший."),
            ("read", "читать", "ри:д",
             "I read before sleep.", "Я читаю перед сном."),
            ("watch", "смотреть", "уОч",
             "We watch films in the evening.", "Вечером мы смотрим фильмы."),
            ("listen", "слушать", "лИсн",
             "Listen to me, please.", "Послушайте меня, пожалуйста."),
            ("play", "играть", "плэй",
             "The children play in the park.", "Дети играют в парке."),
            ("swim", "плавать", "суим",
             "I can swim well.", "Я хорошо умею плавать."),
            ("walk", "гулять, ходить пешком", "уОок",
             "We walk in the evening.", "Мы гуляем вечером."),
            ("dance", "танцевать", "даанс",
             "She dances very well.", "Она очень хорошо танцует."),
        ],
    },
    {
        "id": "travel",
        "title": "Путешествия",
        "emoji": "✈️",
        "words": [
            ("travel", "путешествовать", "трЭвл",
             "I love to travel.", "Я люблю путешествовать."),
            ("trip", "поездка", "трип",
             "The trip was long.", "Поездка была долгой."),
            ("hotel", "отель", "хоутЭл",
             "Our hotel is in the centre.", "Наш отель в центре."),
            ("country", "страна; деревня", "кАнтри",
             "Which country are you from?", "Из какой вы страны?"),
            ("beach", "пляж", "би:ч",
             "We go to the beach every day.", "Мы ходим на пляж каждый день."),
            ("mountain", "гора", "мАунтин",
             "The mountains are beautiful.", "Горы красивые."),
            ("sea", "море", "си:",
             "The sea is warm in July.", "В июле море тёплое."),
            ("photo", "фотография", "фОутоу",
             "Take a photo, please.", "Сделайте фото, пожалуйста."),
            ("luggage", "багаж", "лАгидж",
             "My luggage is heavy.", "Мой багаж тяжёлый."),
            ("passport", "паспорт", "пАаспо:т",
             "Show your passport, please.", "Покажите паспорт, пожалуйста."),
            ("booking", "бронирование", "бУкинг",
             "I have a booking for two nights.", "У меня бронь на две ночи."),
            ("visit", "посещать, навещать", "вИзит",
             "We visit our parents every month.", "Мы навещаем родителей каждый месяц."),
        ],
    },
    {
        "id": "feelings",
        "title": "Чувства и желания",
        "emoji": "😊",
        "words": [
            ("happy", "счастливый, рад", "хЭпи",
             "I am happy to see you.", "Я рад тебя видеть."),
            ("sad", "грустный", "сэд",
             "Why are you sad?", "Почему ты грустный?"),
            ("tired", "уставший", "тАйэд",
             "I am tired after work.", "Я устал после работы."),
            ("angry", "злой, сердитый", "Энгри",
             "Do not be angry with me.", "Не сердись на меня."),
            ("afraid", "бояться, испуганный", "эфрЭйд",
             "I am afraid of dogs.", "Я боюсь собак."),
            ("love", "любить, любовь", "лав",
             "I love my family.", "Я люблю свою семью."),
            ("like", "нравиться", "лайк",
             "I like English.", "Мне нравится английский."),
            ("want", "хотеть", "уонт",
             "I want a cup of coffee.", "Я хочу чашку кофе."),
            ("need", "нуждаться, нужно", "ни:д",
             "I need your help.", "Мне нужна твоя помощь."),
            ("interesting", "интересный", "ИНтрэстинг",
             "This book is interesting.", "Эта книга интересная."),
        ],
    },
    {
        "id": "talk",
        "title": "Общение и речь",
        "emoji": "💬",
        "words": [
            ("speak", "говорить (на языке)", "спи:к",
             "Do you speak English?", "Вы говорите по-английски?"),
            ("talk", "разговаривать", "то:к",
             "We talk every evening.", "Мы разговариваем каждый вечер."),
            ("say", "сказать", "сэй",
             "What did you say?", "Что вы сказали?"),
            ("tell", "рассказать, сказать (кому-то)", "тел",
             "Tell me about your day.", "Расскажи мне о своём дне."),
            ("ask", "спрашивать, просить", "аск",
             "Ask me any question.", "Задай мне любой вопрос."),
            ("answer", "отвечать; ответ", "Аансэ",
             "Please answer my question.", "Пожалуйста, ответьте на мой вопрос."),
            ("question", "вопрос", "куЭсчн",
             "I have a question.", "У меня есть вопрос."),
            ("understand", "понимать", "андэстЭнд",
             "I do not understand you.", "Я вас не понимаю."),
            ("repeat", "повторять", "рипИ:т",
             "Could you repeat it, please?", "Не могли бы вы повторить?"),
            ("language", "язык", "лЭнгвидж",
             "English is an easy language.", "Английский - простой язык."),
        ],
    },
    {
        "id": "verbs",
        "title": "Главные глаголы",
        "emoji": "🔧",
        "words": [
            ("have", "иметь", "хэв",
             "I have a big family.", "У меня большая семья."),
            ("do", "делать", "ду:",
             "What do you do in the evening?", "Что ты делаешь вечером?"),
            ("make", "делать, готовить, создавать", "мэйк",
             "I make breakfast for my family.", "Я готовлю завтрак для семьи."),
            ("go", "идти, ехать", "гОу",
             "I go to work at eight.", "Я иду на работу в восемь."),
            ("come", "приходить", "кам",
             "Come to my house, please.", "Приходи ко мне домой, пожалуйста."),
            ("take", "брать, взять", "тэйк",
             "Take an umbrella, it is raining.", "Возьми зонт, идёт дождь."),
            ("give", "давать", "гив",
             "Give me your phone, please.", "Дай мне телефон, пожалуйста."),
            ("get", "получать, доставать", "гет",
             "I get letters every week.", "Я получаю письма каждую неделю."),
            ("know", "знать", "нОу",
             "I know this city well.", "Я хорошо знаю этот город."),
            ("think", "думать", "синк",
             "I think it is a good idea.", "Я думаю, это хорошая идея."),
        ],
    },
    {
        "id": "adjectives",
        "title": "Главные прилагательные",
        "emoji": "⚖️",
        "words": [
            ("good", "хороший", "гуд",
             "This is a good idea.", "Это хорошая идея."),
            ("bad", "плохой", "бэд",
             "The weather is bad today.", "Сегодня плохая погода."),
            ("new", "новый", "нью:",
             "I have a new phone.", "У меня новый телефон."),
            ("old", "старый", "Оулд",
             "This is an old house.", "Это старый дом."),
            ("big", "большой", "биг",
             "They live in a big city.", "Они живут в большом городе."),
            ("small", "маленький", "смо:л",
             "My flat is small but warm.", "Моя квартира маленькая, но тёплая."),
            ("easy", "лёгкий, простой", "И:зи",
             "The exercise is easy.", "Упражнение лёгкое."),
            ("difficult", "сложный", "дИфикэлт",
             "English grammar is not difficult.", "Английская грамматика не сложная."),
            ("fast", "быстрый, быстро", "фааст",
             "The train is fast.", "Поезд быстрый."),
            ("slow", "медленный, медленно", "слОу",
             "The bus is slow today.", "Автобус сегодня медленный."),
        ],
    },
    {
        "id": "linkwords",
        "title": "Связки и служебные слова",
        "emoji": "🔗",
        "words": [
            ("and", "и", "энд",
             "I speak English and Russian.", "Я говорю по-английски и по-русски."),
            ("but", "но", "бат",
             "I am tired but happy.", "Я устал, но счастлив."),
            ("or", "или", "о:",
             "Tea or coffee?", "Чай или кофе?"),
            ("because", "потому что", "бикОз",
             "I am late because of the traffic.", "Я опоздал из-за пробок."),
            ("also", "также", "Оолсоу",
             "She also speaks French.", "Она также говорит по-французски."),
            ("very", "очень", "вЭри",
             "This soup is very tasty.", "Этот суп очень вкусный."),
            ("too", "слишком; тоже", "ту:",
             "It is too expensive.", "Это слишком дорого."),
            ("only", "только", "Оунли",
             "I have only one question.", "У меня только один вопрос."),
            ("maybe", "может быть", "мЭйби",
             "Maybe we will go tomorrow.", "Может быть, мы поедем завтра."),
            ("of course", "конечно", "оф кОос",
             "Of course you can come!", "Конечно, ты можешь прийти!"),
        ],
    },
]
