# -*- coding: utf-8 -*-
"""Словарь курса, часть 4 (темы 31-33: учёба, техника, природа). Формат см. words1.py."""

TOPICS = [
    {
        "id": "school",
        "title": "Учёба и школа",
        "emoji": "🎓",
        "words": [
            ("school", "школа", "ску:л",
             "My son goes to school.", "Мой сын ходит в школу."),
            ("teacher", "учитель", "тИ:чэ",
             "Our teacher speaks English.", "Наш учитель говорит по-английски."),
            ("student", "студент, ученик", "стьЮ:дэнт",
             "She is a good student.", "Она хорошая ученица."),
            ("lesson", "урок, занятие", "лЭсн",
             "The lesson starts at nine.", "Урок начинается в девять."),
            ("homework", "домашнее задание", "хОумуЁрк",
             "I do my homework in the evening.", "Я делаю домашнее задание вечером."),
            ("exam", "экзамен", "игзЭм",
             "The exam is on Friday.", "Экзамен в пятницу."),
            ("class", "класс, группа, занятие", "клаас",
             "Our class is small.", "Наша группа маленькая."),
            ("notebook", "тетрадь, блокнот", "нОутбук",
             "Open your notebook, please.", "Откройте тетрадь, пожалуйста."),
            ("learn", "учить, узнавать", "лЁн",
             "I learn English every day.", "Я учу английский каждый день."),
            ("word", "слово", "уЁд",
             "I learn ten new words a day.", "Я учу десять новых слов в день."),
            ("sentence", "предложение", "сЭнтэнс",
             "Make a sentence with this word.", "Составьте предложение с этим словом."),
            ("mistake", "ошибка", "мистЭйк",
             "I make mistakes, but I learn.", "Я делаю ошибки, но я учусь."),
        ],
    },
    {
        "id": "tech",
        "title": "Техника и интернет",
        "emoji": "💻",
        "words": [
            ("computer", "компьютер", "компьЮ:тэ",
             "My computer is very old.", "Мой компьютер очень старый."),
            ("internet", "интернет", "Интэнэт",
             "I work on the internet.", "Я работаю в интернете."),
            ("email", "электронное письмо", "И:мэйл",
             "I get ten emails a day.", "Я получаю десять писем в день."),
            ("message", "сообщение", "мЭсидж",
             "Send me a message, please.", "Отправь мне сообщение, пожалуйста."),
            ("file", "файл", "файл",
             "This file is important.", "Этот файл важный."),
            ("screen", "экран", "скри:н",
             "The screen is too small.", "Экран слишком маленький."),
            ("password", "пароль", "пАасуЁд",
             "I forgot my password.", "Я забыл свой пароль."),
            ("camera", "камера, фотоаппарат", "кЭмэрэ",
             "This camera is very good.", "Эта камера очень хорошая."),
            ("battery", "батарея, аккумулятор", "бЭтэри",
             "My phone battery is low.", "У моего телефона садится батарея."),
            ("charge", "заряжать", "чаадж",
             "I charge my phone at night.", "Я заряжаю телефон ночью."),
            ("app", "приложение", "эп",
             "This app helps me learn words.", "Это приложение помогает мне учить слова."),
            ("download", "скачивать", "даунлОуд",
             "I download books to my phone.", "Я скачиваю книги в телефон."),
        ],
    },
    {
        "id": "nature",
        "title": "Природа и животные",
        "emoji": "🌳",
        "words": [
            ("animal", "животное", "Энимэл",
             "What is your favourite animal?", "Какое твоё любимое животное?"),
            ("bird", "птица", "бЁд",
             "A bird is singing in the garden.", "В саду поёт птица."),
            ("horse", "лошадь", "хОос",
             "The horse is very big.", "Лошадь очень большая."),
            ("river", "река", "рИвэ",
             "We swim in the river in summer.", "Летом мы купаемся в реке."),
            ("lake", "озеро", "лэйк",
             "The lake is near our house.", "Озеро рядом с нашим домом."),
            ("forest", "лес", "фОрист",
             "We walk in the forest on Sunday.", "В воскресенье мы гуляем в лесу."),
            ("field", "поле", "фи:лд",
             "There are horses in the field.", "В поле есть лошади."),
            ("stone", "камень", "стОун",
             "The house is made of stone.", "Дом построен из камня."),
            ("fire", "огонь, костёр", "фАйэ",
             "We make a fire in the evening.", "Вечером мы разводим костёр."),
            ("ice", "лёд", "айс",
             "There is ice on the lake in winter.", "Зимой на озере лёд."),
            ("island", "остров", "Айлэнд",
             "We had a holiday on a small island.", "Мы отдыхали на маленьком острове."),
            ("cloud", "облако, туча", "клАуд",
             "There are no clouds in the sky.", "На небе нет облаков."),
        ],
    },
]
