# -*- coding: utf-8 -*-
"""Словарь курса, часть 2 (темы 11-20). Формат см. words1.py."""

TOPICS = [
    {
        "id": "days",
        "title": "Дни недели",
        "emoji": "📅",
        "words": [
            ("Monday", "понедельник", "мАндэй",
             "On Monday I have English.", "В понедельник у меня английский."),
            ("Tuesday", "вторник", "тьЮ:здэй",
             "The meeting is on Tuesday.", "Встреча во вторник."),
            ("Wednesday", "среда", "уЭнздэй",
             "Wednesday is my busy day.", "Среда - мой занятой день."),
            ("Thursday", "четверг", "сЁздэй",
             "We play football on Thursday.", "В четверг мы играем в футбол."),
            ("Friday", "пятница", "фрАйдэй",
             "Friday evening is free.", "Вечер пятницы свободен."),
            ("Saturday", "суббота", "сЭтэдэй",
             "On Saturday I sleep late.", "В субботу я сплю долго."),
            ("Sunday", "воскресенье", "сАндэй",
             "Sunday is a family day.", "Воскресенье - семейный день."),
            ("weekend", "выходные", "уикЭнд",
             "Have a nice weekend!", "Хороших выходных!"),
            ("weekday", "будний день", "уИ:кдэй",
             "I work on weekdays.", "Я работаю по будням."),
            ("holiday", "праздник, отпуск", "хОлидэй",
             "My holiday starts tomorrow.", "Мой отпуск начинается завтра."),
        ],
    },
    {
        "id": "routine",
        "title": "Распорядок дня",
        "emoji": "🌅",
        "words": [
            ("wake up", "просыпаться", "уЭйк ап",
             "I wake up at seven.", "Я просыпаюсь в семь."),
            ("get up", "вставать", "гет ап",
             "He gets up early.", "Он встаёт рано."),
            ("wash", "мыть(ся), умываться", "уОш",
             "I wash my hands.", "Я мою руки."),
            ("have breakfast", "завтракать", "хэв брЭкфэст",
             "We have breakfast together.", "Мы завтракаем вместе."),
            ("go to work", "идти на работу", "гОу ту уЁрк",
             "I go to work by metro.", "Я еду на работу на метро."),
            ("work", "работать, работа", "уЁрк",
             "She works in a bank.", "Она работает в банке."),
            ("study", "учиться, изучать", "стАди",
             "I study English every day.", "Я учу английский каждый день."),
            ("come home", "приходить домой", "кам хОум",
             "I come home at six.", "Я прихожу домой в шесть."),
            ("go to bed", "ложиться спать", "гОу ту бэд",
             "The child goes to bed at nine.", "Ребёнок ложится спать в девять."),
            ("sleep", "спать, сон", "сли:п",
             "I sleep seven hours.", "Я сплю семь часов."),
            ("rest", "отдыхать, отдых", "рест",
             "We rest at the weekend.", "Мы отдыхаем на выходных."),
            ("start", "начинать(ся)", "ста:т",
             "The film starts at eight.", "Фильм начинается в восемь."),
        ],
    },
    {
        "id": "home",
        "title": "Дом и квартира",
        "emoji": "🏠",
        "words": [
            ("house", "дом (здание)", "хАус",
             "Their house is big.", "Их дом большой."),
            ("flat", "квартира", "флэт",
             "I live in a small flat.", "Я живу в маленькой квартире."),
            ("room", "комната", "ру:м",
             "This room is very light.", "Эта комната очень светлая."),
            ("kitchen", "кухня", "кИтчин",
             "Mum is in the kitchen.", "Мама на кухне."),
            ("bathroom", "ванная комната", "бАасру:м",
             "The bathroom is over there.", "Ванная там."),
            ("bed", "кровать", "бэд",
             "The cat is on the bed.", "Кошка на кровати."),
            ("sofa", "диван", "сОуфа",
             "We watch TV on the sofa.", "Мы смотрим телевизор на диване."),
            ("lamp", "лампа", "лэмп",
             "Turn on the lamp, please.", "Включите лампу, пожалуйста."),
            ("floor", "пол, этаж", "фло:",
             "My flat is on the third floor.", "Моя квартира на третьем этаже."),
            ("garden", "сад", "гАадн",
             "Grandma works in the garden.", "Бабушка работает в саду."),
            ("wall", "стена", "уОол",
             "The picture is on the wall.", "Картина на стене."),
            ("mirror", "зеркало", "мИрэ",
             "Look in the mirror.", "Посмотри в зеркало."),
        ],
    },
    {
        "id": "city",
        "title": "Город",
        "emoji": "🏙",
        "words": [
            ("street", "улица", "стри:т",
             "I live in a quiet street.", "Я живу на тихой улице."),
            ("road", "дорога", "рОуд",
             "The road is long.", "Дорога длинная."),
            ("park", "парк", "па:к",
             "We walk in the park.", "Мы гуляем в парке."),
            ("shop", "магазин", "шоп",
             "The shop is closed today.", "Магазин сегодня закрыт."),
            ("pharmacy", "аптека", "фАамэси",
             "Is there a pharmacy near here?", "Здесь рядом есть аптека?"),
            ("bank", "банк", "бэнк",
             "The bank opens at nine.", "Банк открывается в девять."),
            ("station", "вокзал, станция", "стЭйшн",
             "The station is far from here.", "Вокзал далеко отсюда."),
            ("square", "площадь", "скуЭэ",
             "The square is very big.", "Площадь очень большая."),
            ("bridge", "мост", "бридж",
             "Go over the bridge.", "Идите через мост."),
            ("centre", "центр", "сЭнтэ",
             "The city centre is beautiful.", "Центр города красивый."),
            ("market", "рынок", "мАакит",
             "We buy food at the market.", "Мы покупаем еду на рынке."),
            ("church", "церковь", "чЁч",
             "This church is old.", "Эта церковь старая."),
        ],
    },
    {
        "id": "transport",
        "title": "Транспорт",
        "emoji": "🚌",
        "words": [
            ("bus", "автобус", "бас",
             "I go by bus.", "Я езжу на автобусе."),
            ("car", "машина", "ка:",
             "His car is new.", "Его машина новая."),
            ("train", "поезд", "трэйн",
             "The train leaves at six.", "Поезд уходит в шесть."),
            ("metro", "метро", "мЭтроу",
             "The metro is fast.", "Метро быстрое."),
            ("taxi", "такси", "тЭкси",
             "Let us take a taxi.", "Давай возьмём такси."),
            ("plane", "самолёт", "плэйн",
             "The plane is late.", "Самолёт задерживается."),
            ("ticket", "билет", "тИкит",
             "One ticket to London, please.", "Один билет до Лондона, пожалуйста."),
            ("stop", "остановка; останавливаться", "стоп",
             "The bus stop is over there.", "Автобусная остановка вон там."),
            ("airport", "аэропорт", "Ээпо:т",
             "The airport is far.", "Аэропорт далеко."),
            ("drive", "водить машину", "драйв",
             "She drives very well.", "Она очень хорошо водит."),
            ("ride", "ехать (верхом, на велосипеде)", "райд",
             "I ride a bike to work.", "Я езжу на работу на велосипеде."),
            ("leave", "уезжать, покидать", "ли:в",
             "We leave on Friday.", "Мы уезжаем в пятницу."),
        ],
    },
    {
        "id": "directions",
        "title": "Как пройти",
        "emoji": "🧭",
        "words": [
            ("left", "налево, левый", "лефт",
             "Turn left at the corner.", "Поверните налево на углу."),
            ("right", "направо, правый", "райт",
             "Go right, then straight.", "Идите направо, потом прямо."),
            ("straight", "прямо", "стрэйт",
             "Go straight for five minutes.", "Идите прямо пять минут."),
            ("near", "рядом, близко", "ниэ",
             "Is the shop near?", "Магазин близко?"),
            ("far", "далеко", "фа:",
             "The station is far from here.", "Вокзал далеко отсюда."),
            ("here", "здесь", "хиэ",
             "Come here, please.", "Идите сюда, пожалуйста."),
            ("there", "там", "ЗЭэ",
             "My office is there.", "Мой офис там."),
            ("turn", "поворачивать", "тЁн",
             "Turn right after the bank.", "Поверните направо после банка."),
            ("corner", "угол", "кОонэ",
             "The cafe is on the corner.", "Кафе на углу."),
            ("map", "карта", "мэп",
             "Look at the map.", "Посмотрите на карту."),
        ],
    },
    {
        "id": "shopping",
        "title": "Покупки и деньги",
        "emoji": "🛒",
        "words": [
            ("price", "цена", "прайс",
             "The price is very good.", "Цена очень хорошая."),
            ("money", "деньги", "мАни",
             "I have no money today.", "У меня сегодня нет денег."),
            ("cheap", "дешёвый", "чи:п",
             "This bag is cheap.", "Эта сумка дешёвая."),
            ("expensive", "дорогой", "икспЭнсив",
             "The car is too expensive.", "Машина слишком дорогая."),
            ("buy", "покупать", "бай",
             "I want to buy a phone.", "Я хочу купить телефон."),
            ("pay", "платить", "пэй",
             "Can I pay by card?", "Можно заплатить картой?"),
            ("cash", "наличные", "кэш",
             "I pay in cash.", "Я плачу наличными."),
            ("card", "карта (банковская)", "ка:д",
             "Here is my card.", "Вот моя карта."),
            ("size", "размер", "сайз",
             "What size do you need?", "Какой размер вам нужен?"),
            ("change", "сдача; менять", "чЭйндж",
             "Here is your change.", "Вот ваша сдача."),
        ],
    },
    {
        "id": "clothes",
        "title": "Одежда",
        "emoji": "👕",
        "words": [
            ("shirt", "рубашка", "шЁт",
             "He wears a white shirt.", "Он носит белую рубашку."),
            ("T-shirt", "футболка", "тИ:шЁт",
             "I like this blue T-shirt.", "Мне нравится эта синяя футболка."),
            ("trousers", "брюки", "трАузэз",
             "These trousers are new.", "Эти брюки новые."),
            ("dress", "платье", "дрэс",
             "Her dress is beautiful.", "Её платье красивое."),
            ("shoes", "обувь, туфли", "шу:з",
             "My shoes are old.", "Моя обувь старая."),
            ("jacket", "куртка, пиджак", "джЭкит",
             "Take your jacket, it is cold.", "Возьми куртку, холодно."),
            ("coat", "пальто", "кОут",
             "This coat is warm.", "Это пальто тёплое."),
            ("hat", "шапка, шляпа", "хэт",
             "He wears a hat in winter.", "Он носит шапку зимой."),
            ("socks", "носки", "сокс",
             "I need new socks.", "Мне нужны новые носки."),
            ("wear", "носить (одежду)", "уЭэ",
             "She wears glasses.", "Она носит очки."),
        ],
    },
    {
        "id": "body",
        "title": "Тело и здоровье",
        "emoji": "🩺",
        "words": [
            ("head", "голова", "хэд",
             "My head hurts.", "У меня болит голова."),
            ("arm", "рука (от плеча)", "а:м",
             "He broke his arm.", "Он сломал руку."),
            ("leg", "нога", "лэг",
             "My leg is fine now.", "Моя нога теперь в порядке."),
            ("eye", "глаз", "ай",
             "She has green eyes.", "У неё зелёные глаза."),
            ("ear", "ухо", "Иэ",
             "My ear hurts.", "У меня болит ухо."),
            ("hand", "рука (кисть)", "хэнд",
             "Wash your hands, please.", "Помойте руки, пожалуйста."),
            ("back", "спина; назад", "бэк",
             "My back hurts after work.", "У меня болит спина после работы."),
            ("ill", "больной", "ил",
             "I am ill today.", "Я сегодня болею."),
            ("doctor", "врач", "дОктэ",
             "You must see a doctor.", "Тебе нужно к врачу."),
            ("medicine", "лекарство", "мЭдсин",
             "Take this medicine twice a day.", "Принимайте это лекарство два раза в день."),
            ("pain", "боль", "пэйн",
             "I have a pain in my leg.", "У меня боль в ноге."),
            ("feel", "чувствовать себя", "фи:л",
             "How do you feel today?", "Как вы себя чувствуете сегодня?"),
        ],
    },
    {
        "id": "weather",
        "title": "Погода и природа",
        "emoji": "🌦",
        "words": [
            ("weather", "погода", "уЭЗэ",
             "The weather is nice today.", "Сегодня хорошая погода."),
            ("sun", "солнце", "сан",
             "The sun is hot.", "Солнце жаркое."),
            ("rain", "дождь", "рэйн",
             "It is going to rain.", "Скоро будет дождь."),
            ("snow", "снег", "снОу",
             "I like snow in winter.", "Я люблю снег зимой."),
            ("wind", "ветер", "уинд",
             "The wind is strong today.", "Сегодня сильный ветер."),
            ("cold", "холодный, холодно", "кОулд",
             "It is cold outside.", "На улице холодно."),
            ("warm", "тёплый, тепло", "уОом",
             "The water is warm.", "Вода тёплая."),
            ("hot", "жаркий, горячий", "хот",
             "It is hot in summer.", "Летом жарко."),
            ("sky", "небо", "скай",
             "The sky is grey.", "Небо серое."),
            ("tree", "дерево", "три:",
             "There is a big tree in the garden.", "В саду большое дерево."),
        ],
    },
]
